wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.16.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710730711.0
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 23
      - 37
      4: 3.10.5
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 2000
embedding_size:
  desc: null
  value: 64
in_channels:
  desc: null
  value: 9
kernel_size:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.01
model_type:
  desc: null
  value: UNet
n_encoders:
  desc: null
  value: 2
out_channels:
  desc: null
  value: 4
scale_factor:
  desc: null
  value: 50
model_params:
  desc: null
  value:
    depth: 2
    n_encoders: 2
    embedding_size: 64
    pool_sizes:
    - 5
    - 5
    - 2
    kernel_size: 3
    scale_factor: 50
